name: budparr
favicon: null
layout_spectrum: 0.5724314094986767
typography_spectrum: 0.5982905165292323
title: Bud Parr
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#f3e3d6'
    - '#411b0e'
    - '#a56134'
    - '#cd915d'
  brandStrength: 0
  lightness: 0.6146070794202387
  saturation: 0.5621028542518616
  rhythmicContrast: 0.2874122413340956
purpose: []
